export const categorySpend = [
  {
    id: 1,
    name: "Ăn uống",
    icon: "hamburger",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 3,
        name: "Cafe",
        icon: "coffee",
        iconLib: "FontAwesome5",
        hanmuccha: "1",
      },
      {
        id: 4,
        name: "Ăn sáng",
        icon: "utensils",
        iconLib: "FontAwesome5",
        hanmuccha: "1",
      },
      {
        id: 5,
        name: "Ăn trưa",
        icon: "utensils",
        iconLib: "FontAwesome5",
        hanmuccha: "1",
      },
      {
        id: 8,
        name: "Đi chợ",
        icon: "shopping-cart",
        iconLib: "FontAwesome5",
        hanmuccha: "1",
      },
    ],
  },
  {
    id: 6,
    name: "Dịch vụ sinh hoạt",
    icon: "file-invoice",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 7,
        name: "Điện",
        icon: "bolt",
        iconLib: "FontAwesome5",
        hanmuccha: "6",
      },
      {
        id: 10,
        name: "Nước",
        icon: "water",
        iconLib: "FontAwesome5",
        hanmuccha: "6",
      },
      {
        id: 11,
        name: "Internet",
        icon: "wifi",
        iconLib: "FontAwesome5",
        hanmuccha: "6",
      },
    ],
  },
  {
    id: 12,
    name: "Đi lại",
    icon: "car",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 13,
        name: "Xăng xe",
        icon: "gas-pump",
        iconLib: "FontAwesome5",
        hanmuccha: "12",
      },
      {
        id: 14,
        name: "Bảo hiểm xe",
        icon: "car-crash",
        iconLib: "FontAwesome5",
        hanmuccha: "12",
      },
      {
        id: 15,
        name: "Sửa chữa, bảo dưỡng xe",
        icon: "tools",
        iconLib: "FontAwesome5",
        hanmuccha: "12",
      },
    ],
  },
  {
    id: 16,
    name: "Con cái",
    icon: "child",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 17,
        name: "Học phí",
        icon: "school",
        iconLib: "FontAwesome5",
        hanmuccha: "16",
      },
      {
        id: 18,
        name: "Đồ chơi",
        icon: "puzzle-piece",
        iconLib: "FontAwesome5",
        hanmuccha: "16",
      },
      {
        id: 19,
        name: "Tiền tiêu vặt",
        icon: "coins",
        iconLib: "FontAwesome5",
        hanmuccha: "16",
      },
    ],
  },
  {
    id: 20,
    name: "Mua sắm",
    icon: "shopping-bag",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 21,
        name: "Trang phục",
        icon: "tshirt",
        iconLib: "FontAwesome5",
        hanmuccha: "20",
      },
      {
        id: 22,
        name: "Trang sức",
        icon: "gem",
        iconLib: "FontAwesome5",
        hanmuccha: "20",
      },
      {
        id: 23,
        name: "Phụ kiện",
        icon: "hat-wizard",
        iconLib: "FontAwesome5",
        hanmuccha: "20",
      },
    ],
  },
  {
    id: 24,
    name: "Sức khỏe",
    icon: "heartbeat",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 25,
        name: "Khám chữa bệnh",
        icon: "hospital",
        iconLib: "FontAwesome5",
        hanmuccha: "24",
      },
      {
        id: 26,
        name: "Thuốc men",
        icon: "pills",
        iconLib: "FontAwesome5",
        hanmuccha: "24",
      },
      {
        id: 27,
        name: "Thể thao",
        icon: "running",
        iconLib: "FontAwesome5",
        hanmuccha: "24",
      },
    ],
  },
  {
    id: 28,
    name: "Nhà cửa",
    icon: "home",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
    children: [
      {
        id: 30,
        name: "Mua sắm đồ đạc",
        icon: "couch",
        iconLib: "FontAwesome5",
        hanmuccha: "28",
      },
      {
        id: 31,
        name: "Sửa chữa nhà cửa",
        icon: "hammer",
        iconLib: "FontAwesome5",
        hanmuccha: "28",
      },
      {
        id: 32,
        name: "Thuê nhà",
        icon: "building",
        iconLib: "FontAwesome5",
        hanmuccha: "28",
      },
    ],
  },
];

export const categoryCollect = [
  {
    id: 34,
    name: "Lương",
    icon: "money-bill-wave",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
  },
  {
    id: 35,
    name: "Thưởng",
    icon: "gift",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
  },
  {
    id: 36,
    name: "Được cho/tặng",
    icon: "hand-holding-heart",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
  },
  {
    id: 37,
    name: "Tiền lãi",
    icon: "coins",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
  },
  {
    id: 38,
    name: "Khác",
    icon: "ellipsis-h",
    iconLib: "FontAwesome5",
    hanmuccha: "0",
  },
];

export const iconList = [
  { icon: "hamburger", iconLib: "FontAwesome5" },
  { icon: "coffee", iconLib: "FontAwesome5" },
  { icon: "utensils", iconLib: "FontAwesome5" },
  { icon: "car", iconLib: "FontAwesome5" },
  { icon: "home", iconLib: "FontAwesome5" },
  { icon: "shopping-cart", iconLib: "FontAwesome5" },
  { icon: "couch", iconLib: "FontAwesome5" },
  { icon: "heartbeat", iconLib: "FontAwesome5" },
  { icon: "tools", iconLib: "FontAwesome5" },
  { icon: "bicycle", iconLib: "FontAwesome5" },
  { icon: "laptop", iconLib: "FontAwesome5" },
  { icon: "camera", iconLib: "FontAwesome5" },
  { icon: "gift", iconLib: "FontAwesome5" },
  { icon: "apple-alt", iconLib: "FontAwesome5" },
  { icon: "dog", iconLib: "FontAwesome5" },
  { icon: "puzzle-piece", iconLib: "FontAwesome5" },
  { icon: "money-bill-wave", iconLib: "FontAwesome5" },
  { icon: "futbol", iconLib: "FontAwesome5" },
  { icon: "paint-brush", iconLib: "FontAwesome5" },
  { icon: "music", iconLib: "FontAwesome5" },
  { icon: "file-invoice", iconLib: "FontAwesome5" },
  { icon: "bolt", iconLib: "FontAwesome5" },
  { icon: "water", iconLib: "FontAwesome5" },
  { icon: "wifi", iconLib: "FontAwesome5" },
  { icon: "gas-pump", iconLib: "FontAwesome5" },
  { icon: "car-crash", iconLib: "FontAwesome5" },
  { icon: "child", iconLib: "FontAwesome5" },
  { icon: "school", iconLib: "FontAwesome5" },
  { icon: "coins", iconLib: "FontAwesome5" },
  { icon: "tshirt", iconLib: "FontAwesome5" },
  { icon: "gem", iconLib: "FontAwesome5" },
  { icon: "hat-wizard", iconLib: "FontAwesome5" },
  { icon: "hospital", iconLib: "FontAwesome5" },
  { icon: "pills", iconLib: "FontAwesome5" },
  { icon: "running", iconLib: "FontAwesome5" },
  { icon: "hammer", iconLib: "FontAwesome5" },
  { icon: "building", iconLib: "FontAwesome5" },
  { icon: "hand-holding-heart", iconLib: "FontAwesome5" },
  { icon: "ellipsis-h", iconLib: "FontAwesome5" },
];
